export const SET_CURRENT_FRAME_INDEX = 'SET_CURRENT_FRAME_INDEX';
export const SET_TOTAL_PINS = 'SET_TOTAL_PINS';
export const SET_PLAYER_SCORE = 'SET_PLAYER_SCORE';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const SET_TOTAL_PLAYERS = 'SET_TOTAL_PLAYERS';