export const SET_CURRENT_FRAME_INDEX = 'SET_CURRENT_FRAME_INDEX';
export const SET_CURRENT_ROLL = 'SET_CURRENT_ROLL';
export const SET_PLAYER_SCORE = 'SET_PLAYER_SCORE';
export const ADD_PLAYER = 'ADD_PLAYER';
export const ADD_GAME = 'ADD_GAME';
export const SET_CURRENT_GAME = 'SET_CURRENT_GAME';
export const SET_HAS_SPARE = 'SET_HAS_SPARE';
export const SET_HAS_STRIKE = 'SET_HAS_STRIKE';